services:
  app-db:
    image: postgres:latest
    container_name: app-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    expose:
      - 5432
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - app-db:/var/lib/postgresql/data
    networks:
      - app-network
  laravel-nginx:
    build:
      context: ../
      dockerfile: docker/dockerfile
    container_name: laravel-nginx
    restart: unless-stopped
    tty: true
    depends_on:
      - app-db
    networks:
      - app-network
    ports:
      - "80:${WEB_PORT_HTTP}"
      - "443:${WEB_PORT_SSL}"
    environment:
      - DB_HOST=app-db
    volumes:
      - ../.:/var/www/html
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    entrypoint: ["/bin/sh", "-c", "./start.sh"]

networks:
  app-network:
    driver: bridge

volumes:
  app-db:
    driver: local
